# Generated by Django 4.0.6 on 2022-08-01 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_account_customer_id_number_customer_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=10, null=True)),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('Amount', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Customer',
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_account', to='Wallet.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='Wallet.customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='Date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_charge', models.IntegerField(null=True)),
                ('Date_time', models.DateTimeField(null=True)),
                ('Wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction', to='Wallet.wallet')),
                ('destination_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_transaction', to='Wallet.account')),
                ('origin_Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_transaction', to='Wallet.account')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Third_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('currency', models.IntegerField(null=True)),
                ('transaction_cost', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_party_account', to='Wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reward', models.DateTimeField(null=True)),
                ('points', models.BigIntegerField(null=True)),
                ('recepient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepient_rewards', to='Wallet.wallet')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walllet_reward', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=10, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_transaction', to='Wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10, null=True)),
                ('title', models.CharField(max_length=10, null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('recepient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepient_notification', to='Wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(null=True)),
                ('purpose', models.CharField(max_length=10, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('loan_status', models.CharField(max_length=10, null=True)),
                ('date_issued', models.DateTimeField(null=True)),
                ('interest_rate', models.IntegerField(null=True)),
                ('payment_due_date', models.DateTimeField(null=True)),
                ('loan_balance', models.IntegerField(null=True)),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_guarantor', to='Wallet.customer')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_wallet', to='Wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(null=True)),
                ('card_name', models.CharField(max_length=10, null=True)),
                ('Date_issued', models.DateTimeField(null=True, verbose_name=datetime.datetime.now)),
                ('card_type', models.CharField(max_length=10, null=True)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('security_code', models.IntegerField(null=True)),
                ('issuer', models.CharField(max_length=20, null=True)),
                ('signature', models.CharField(max_length=5, null=True)),
                ('Account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_card', to='Wallet.customer')),
            ],
        ),
    ]
