# Generated by Django 4.0.6 on 2022-08-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_currency_remove_wallet_customer_account_wallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Date_of_registration',
            field=models.DateTimeField(null=True),
        ),
    ]
