# Generated by Django 4.0.6 on 2022-08-19 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_customer_date_of_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Date_of_registration',
            new_name='date_of_registration',
        ),
    ]
