# Generated by Django 4.0.6 on 2022-08-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_rename_date_of_registration_customer_date_of_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='Amount',
            new_name='amount',
        ),
    ]
