# Generated by Django 4.0.6 on 2022-08-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_rename_amount_currency_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='Date_issued',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ID_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Date_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Wallet',
            new_name='wallet',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Date_created',
            new_name='date_created',
        ),
    ]
